# Generated by Django 4.2.30 on 2026-07-15 21:02

from django.db import migrations, models
import django.db.models.deletion
import monitoring.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField(default='127.0.0.1')),
                ('port', models.PositiveIntegerField(default=22)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', monitoring.fields.EncryptedTextField(blank=True)),
                ('is_local', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('last_status', models.CharField(default='unknown', max_length=20)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_local', 'name'],
                'indexes': [models.Index(fields=['enabled', 'is_local'], name='monitoring__enabled_a4aaa5_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', '正常'), ('warning', '警告'), ('critical', '严重')], default='info', max_length=20)),
                ('problem', models.CharField(blank=True, max_length=500)),
                ('content', models.JSONField(default=dict)),
                ('created_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_reports', to='monitoring.server')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='MetricRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.FloatField()),
                ('memory', models.FloatField()),
                ('disk', models.FloatField()),
                ('network_in', models.FloatField(default=0)),
                ('network_out', models.FloatField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='monitoring.server')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['server', '-timestamp'], name='monitoring__server__dc8c4e_idx')],
            },
        ),
    ]
